### ISSUE TITLE
should.not.exist is not a function

### ISSUE THREAD

**Issue by alexjeffburke** [gustavnikolaj/should-be-unexpected#4]
Seems that should.not.exist() doesn't work when using should-be-unexpected. Happen to have this construct all through a test suite I'm working on, so this is that belated report I promised when trying to swap to using this in a few more places :)

**Comment by alexjeffburke** [comment]
Me being daft. Apols - I will try to use this even more in earnest though. Alex

**Comment by gustavnikolaj** [comment]
Hehe... What happened here? :-) Now I'm curious!
